---
- name: Create Network
  community.docker.docker_network:
    name: "{{ network_name }}"
    driver: overlay

- name: Deploy Services
  include_tasks: "/home/vagrant/ansible/roles/deploy/services/{{ item.name }}/service.yml" 
  vars:
    - name: "{{ item.name }}"
    - version: "{{ item.version }}"
  loop: "{{ services }}"
