---
- name: Preconfig
  hosts: cluster
  tasks:
    - name: Install Docker
      become: true
      block:
        - name: Adding Universe Repo
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
            state: present

        - name: Install additional packages
          apt:
            name:
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            update-cache: true
            cache_valid_time: 86400

        - name: Add key-file for Docker
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
            keyring: /usr/share/keyrings/docker-archive-keyring.gpg

        - name: Add stable Docker repo
          apt_repository:
            repo: >
              deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
              https://download.docker.com/linux/ubuntu
              {{ ansible_distribution_release }} stable
            state: present
            update-cache: true
            filename: docker

        - name: Install Docker-CE
          apt:
            name: docker-ce
            update-cache: true

        - name: Checking that Docker is installed and restarted
          service:
            name: docker
            state: restarted
            enabled: true

    - name: Get and Install Latest Version of Docker Compose
      become: true
      block:
        - name: Get Docker Compose
          uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json
          register: page

        - name: Install Docker Compose
          get_url:
            url: https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64
            dest: /usr/local/bin/docker-compose
            mode: 0755

    - name: Finishing Install
      become: true
      block:
        - name: Add user to Docker group
          user:
            name: vagrant
            groups:
              - docker
            append: true

        - name: Reboot the machine
          reboot:
