---
- name: "Deploying Server"
  tags: "{{ name }}"
  block:
  - name: "Deploying Service: [{{ name }}]"
    community.docker.docker_swarm_service:
      name: "{{ name }}"
      image: "{{ registry_name }}/{{ name }}:{{ version }}"
      state: present
      networks:
        - name: "{{ network_name }}"
      publish:
        - mode: ingress
          protocol: tcp
          published_port: 3001
          target_port: 80
