---
- name: "Create Secret for [{{ name }}]"
  vars:
    env_file: "{{ lookup('template', '{{ name }}/.env.j2') }}"
#    env_file: "{{ lookup('file', '{{ name }}/.env') }}"
  community.docker.docker_secret:
    name: "{{ name }}.env"
    data: "{{ env_file | b64encode }}"
    labels:
      secret: "{{ env_file | hash('sha1') }}"
    data_is_b64: true
    force: true
    state: present

# This is not secure, but useful for debugging
- name: "Debug"
  vars:
    env_file: "{{ lookup('template', '{{ name }}/.env.j2') }}"
  debug:
    msg: "{{ env_file }}"
